site_name: Notes
repo_url: https://github.com/gdemare/notes/
repo_name: gdemare/notes
edit_uri: edit/main/docs/

# mkdocs.yml
theme:
  language: fr
  name: "material"
  features:
    - content.action.edit # bouton edit
    - content.action.view # bouton voir
    - content.tabs.link
    - content.code.copy
    - content.tabs.link 
     - toc.integrate # réuni le plan et le sommaire
    - header.autohide
    - navigation.tabs #onglet
    - navigation.tabs.sticky #menu avec les onglets tout le temps visible
    - navigation.sections # section dans le menu a gauche
    # - navigation.expand # menu a gauche déroulant ouvert apr défaut
    - navigation.path # affiche le chemin au début de la page.
    - navigation.top # bouton pour remonter en haut
    # - navigation.indexes # pour avoir une page d'index dans chaque partie
  palette:
      scheme: slate
      primary: indigo
      accent: indigo
  font:
    text: Roboto
    code: Roboto Mono
    
  theme:
    icon:
      edit: material/pencil

plugins:
  - search # barre de rechercher
  - mkdocstrings
  - glightbox #pour les images
  - git-revision-date-localized: #pour avoir la date de maj 
      type: date

markdown_extensions:
  - pymdownx.superfences #ajouter box, notes warning, ...
  - pymdownx.tabbed:
      alternate_style: true
  - admonition
  - pymdownx.details # créer des éléments masquables
  - pymdownx.superfences
  - pymdownx.arithmatex:
      generic: true
  - tables
  - pymdownx.tasklist #ajouter les task lists
  - pymdownx.magiclink # transforme les liens en éléments cliquables.
  
extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js