site_name: Mes notes
repo_url: https://github.com/gdemare/notes/
repo_name: gdemare/notes
edit_uri: edit/main/docs/

# mkdocs.yml
theme:
  language: fr
  name: "material"
  features:
    - content.tabs.link
    - navigation.tabs #onglet
    - navigation.tabs.sticky #menu avec les onglets tout le temps visible
    - navigation.sections # section dans le menu a gauche
    # - navigation.expand # menu a gauche déroulant ouvert apr défaut
    - navigation.path # affiche le chemin au début de la page.
    - navigation.top # bouton pour remonter en haut
    # - navigation.indexes # pour avoir une page d'index dans chaque partie
    - content.tabs.link
    # - toc.integrate # réuni le plan et le sommaire
    - content.action.edit # bouton edit
    #- content.action.view # bouton voir
  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default 
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to system preference
  theme:
    icon:
      edit: material/pencil

plugins:
  - search
  - mkdocstrings
  - glightbox #pour les images
  - git-revision-date-localized: #pour avoir la date de maj 
      type: date

markdown_extensions:
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.arithmatex:
      generic: true
  - tables
  
extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

nav:
  - Anglais : 
    - Conjugaison : anglais/conjugaison.md
    - Grammaire : anglais/grammaire.md
    - "Ortographe et vocabulaire" : anglais/ortographe-vocabulaire.md
  - Biologie :
    - Bioinformatique :
      - "Séquençage" : biologie/bioinformatique/sequencage.md
    - Cellule :
      - "ADN et ARN" : biologie/cellule/ADN-ARN.md
      - "ADN et ARN synthèse" : biologie/cellule/ADN-ARN-synthese.md
      - Bactéries : biologie/cellule/bacteries.md
      - "Communication cellulaire" : biologie/cellule/communication-cellulaire.md
      - Métabolites : biologie/cellule/metabolites.md
      - Protéines : biologie/cellule/proteines.md
    - "Méthodes et techniques" : 
      - "Introduction biologie expérimentale" : biologie/methodes-techniques/introduction-biologie-experiementale.md
      - "Spectrométrie de masse" : biologie/methodes-techniques/spectrometrie.md
    - "Physologie animale" : biologie/physiologie-animale/structure-fonction-principes.md
      - Comportement : biologie/physiologie-animale/comportement.md
      - Histologie  : biologie/physiologie-animale/histologie.md
      - "Osmorégulation et excrétion" : biologie/physiologie-animale/osmoregulation-excretion.md
      - Immunologie : biologie/physiologie-animale/immunologie.md
      - Neurobiologie : biologie/physiologie-animale/neurobiologie.md
      - "Système nerveux" : systeme-nerveux.md
  - Communication :
    - 'Expression orale' :
      - Candidater : communication/expression-orale/entretien-embauche.md
      - Rhétorique : communication/expression-orale/rhetorique.md
  - Mathématique :
    - Mathématique : mathematique/mathematique.md
    - Arithmétique :  mathematique/arithmetique.md
    - Geométrie :  mathematique/geometrie.md
    - Modélisation :
      - "Méthodes mixtes" :
        - 'Réseaux de neurones' : mathematique/reseaux-neurones.md
    - "Statistique et probabilités" : 
      - Probabilité : mathematique/probabilite.md
      - Statistique : mathematique/statistique.md
      - "Tests statistiques" : mathematique/tests-statistiques.md
  - 'Physique Chimie' :
    - Chimie : 
      - Thermodynamique : physique-chimie/chimie/thermodynamique.md
    - Physique :
      - Physique : physique-chimie/physique/physique.md
      - Optique : physique-chimie/physique/optique.md
  - 'math jax' : informatique/markdown-math.md