site_name: Mes notes
repo_url: https://github.com/gdemare/notes/
repo_name: gdemare/notes
edit_uri: edit/main/docs/

# mkdocs.yml
theme:
  language: fr
  name: "material"
  features:
    - content.action.edit # bouton edit
    - content.action.view # bouton voir
    - content.tabs.link
    - content.code.copy
    - content.tabs.link 
     - toc.integrate # réuni le plan et le sommaire
    - header.autohide
    - navigation.tabs #onglet
    - navigation.tabs.sticky #menu avec les onglets tout le temps visible
    - navigation.sections # section dans le menu a gauche
    # - navigation.expand # menu a gauche déroulant ouvert apr défaut
    - navigation.path # affiche le chemin au début de la page.
    - navigation.top # bouton pour remonter en haut
    # - navigation.indexes # pour avoir une page d'index dans chaque partie
  palette:
      scheme: slate
      primary: indigo
      accent: indigo
  font:
    text: Roboto
    code: Roboto Mono
    
  theme:
    icon:
      edit: material/pencil

plugins:
  - search
  - mkdocstrings
  - glightbox #pour les images
  - git-revision-date-localized: #pour avoir la date de maj 
      type: date

markdown_extensions:
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.arithmatex:
      generic: true
  - tables
  
extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

nav:
  - Anglais : 
    - Conjugaison : anglais/conjugaison.md
    - Grammaire : anglais/grammaire.md
    - "Ortographe et vocabulaire" : anglais/ortographe-vocabulaire.md
  - Biologie :
    - Biochimie :
      - "Biomolécules" : biologie/biochimie/biomolecules.md
      - "ADN et ARN" : biologie/biochimie/ADN-ARN.md
      - "Les enzymes" : biologie/biochimie/enzymes.md
      - "Les lipides" : biologie/biochimie/sucres.md
      - "Les métabolites" : biologie/biochimie/metabolites.md
      - "Les protéines" : biologie/biochimie/proteines.md
      - "Les sucres" : biologie/biochimie/sucres.md
      - "Réactivité chimique en biologie" : biologie/biochimie/reactivite-chimique-biologie.md
    - "Métabolisme" :
      - "Photosynthèse et métabolisme secondaire" : biologie/biochimie/photosynthese-metabolisme-secondaire.md
    - Bioinformatique :
      - "Séquençage" : biologie/bioinformatique/alignement-sequence.md
    - Cellule :
      - "ADN et ARN synthèse" : biologie/cellule/ADN-ARN-synthese.md
      - Bactéries : biologie/cellule/bacteries.md
      - "Communication cellulaire" : biologie/cellule/communication-cellulaire.md
      - "Cycle cellulaire" : biologie/cellule/cycle-cellulaire.md
      - "Cytosquelette" : biologie/cellule/cytosquelette.md
      - "Matrice extracellulaire et jonctions cellulaires" : biologie/cellule/matrice-extracellulaire-jonctions-cellulaires.md
      - "Organisation cellulaire" : biologie/cellule/organisation-cellulaire.md
      - "Régulation de l'expression génétique" : biologie/cellule/regulation-expression-genique.md
      - Virus : biologie/cellule/virus.md
    - Ecologie :
      - "Biologie de la conservation" : biologie/ecologie/biologie-conservation.md
      - "Ecologie des communautés" : biologie/ecologie/ecologie-communautes.md
      - "Ecosystème et écologie de la restauration" : biologie/ecologie/ecosysteme-ecologie-restauration.md
      - "Evolution des populations" : biologie/ecologie/evolution-population.md
      - "Génétique des populations" : biologie/ecologie/genetique-population.md
      - "Origine de la biodiversité" : biologie/ecologie/origine-biodiversite.md
    - Evolution :
      - "Génétique Mendel" : biologie/evolution/genetique-mendel.md
      - "Génome évolution" : biologie/evolution/genome-evolution.md
      - "Phylogénie" : biologie/evolution/phylogenie.md
      - "Théorie de l'évolution" : biologie/evolution/theorie-evolution.md
    - "Méthodes et techniques" :
      - "Introduction biologie expérimentale" : biologie/methodes-techniques/introduction-biologie-experiementale.md
      - "Clonage" : biologie/methodes-techniques/clonage.md
      - "Génie génétique" : biologie/methodes-techniques/clonage_genie.md
      - "Culture cellulaire" : biologie/methodes-techniques/culture-cellulaire.md
      - "Généralités" : biologie/methodes-techniques/etude_biologie.md
      - "PCR" : biologie/methodes-techniques/etude_pcr.md
      - "Protéines" : biologie/methodes-techniques/etude_proteines.md
      - "Acide nucléique" : biologie/methodes-techniques/etude_acide_nucleique.md
      - "Histologie" : biologie/methodes-techniques/histologie.md
      - "Imagerie" : biologie/methodes-techniques/imagerie.md
      - "Immunomarquage" : biologie/methodes-techniques/immunomarquage.md
      - "Microscopie" : biologie/methodes-techniques/microscopie.md
      - "Spectrométrie de masse" : biologie/methodes-techniques/spectrometrie.md
    - "Physologie animale" :
      - "Nutrition" : biologie/physiologie-animale/nutrition-animaux.md
      - "Physologie cellule animale" : biologie/physiologie-animale/physiologie-cellule-animale.md
      - "Système endorinien" : biologie/physiologie-animale/systeme-endocrinien.md
      - "Structure et fonction" : biologie/physiologie-animale/structure-fonction-principes.md
      - Comportement : biologie/physiologie-animale/comportement.md
      - Histologie  : biologie/physiologie-animale/histologie.md
      - "Osmorégulation et excrétion" : biologie/physiologie-animale/osmoregulation-excretion.md
      - Immunologie : biologie/physiologie-animale/immunologie.md
      - Neurobiologie : biologie/physiologie-animale/neurobiologie.md
      - "Système nerveux" : biologie/physiologie-animale/systeme-nerveux.md
  - "Data Science" :
    - "Méthodes data science" : data-science/methodes-data-science.md
    - "A voir" : data-science/a-voir.md
    - Cartographie : data-science/cartographie.md
    - Classification : 
      - "G Classification" : data-science/classification/classification.md
      - "G Régression" : data-science/classification/regression.md
      - ANOVA : data-science/classification/ANOVA.md
      - "Arbre de décision" : data-science/classification/arbre-de-décision.md
      - "ARMA" : data-science/classification/ARMA.md
      - "Boosting" : data-science/classification/boosting.md
      - "Carte auto adaptative" : data-science/classification/carte-auto-adaptative.md
      - "Centroides" : data-science/classification/centroide.md
      - "Classificateur baysien" : data-science/classification/classificateur-baysien.md
      - "Cluestering des variables" : data-science/classification/clustering-variables.md
      - "Espérance maximale" : data-science/classification/espérance-maximisation.md
      - "Forêt aléatoire" : data-science/classification/forêt-aléatoire.md
      - "Lissage exponentiel" : data-science/classification/lissage-exponentiel.md
      - "Perceptron" : data-science/classification/perceptron.md
      - "Régression linéaire" : data-science/classification/regression-lineaire.md
      - "Régression logistique" : data-science/classification/regression-logistique.md
      - "SVM" : data-science/classification/SVM.md
    - Cluestering : 
      - Cluestering : data-science/cluestering/cluestering.md
      - "CAH" : data-science/cluestering/CAH.md
      - "CFH" : data-science/cluestering/CDH.md
      - "Centres mobiles" : data-science/cluestering/centres-mobiles.md
    - "Dictionnaire Statistique" : data-science/dictionnaire-statistique.md
    - Graphiques : data-science/graphiques.md
    - "Réduction de dimensions" :
      - "Réduction de dimensions" : data-science/reduction-dimensions/reduction-dimension.md
      - ACM : data-science/reduction-dimensions/ACM.md
      - ACP : data-science/reduction-dimensions/ACP.md
      - AFC : data-science/reduction-dimensions/AFC.md
      - "Positionnement multidimensionnel" : data-science/reduction-dimensions/positionnement-multidimensionnel.md
      - "Analyse discriminante" : data-science/reduction-dimensions/analyse-discriminante.md
    - "Réseaux de neurones" :
      - "Couches convulsives" : data-science/reseaux-neurones/couche-convulsive.md
      - "Réseaux de neurones" : data-science/reseaux-neurones/reseaux-neurones.md
    - "Série temporelle" : data-science/serie-temporelle.md
    - Statistique : data-science/statistique.md
    - "Text mining" : data-science/text-mining.md
    - "Traitement des images" : data-science/traitement-image.md
    - "Transformation des données" : data-science/transformation-donnees.md  
  - Mathématique :
    - Mathématique : mathematique/mathematique.md
    - Algorithmie :  mathematique/algorithmique.md
    - Arithmétique :  mathematique/arithmetique.md
    - Fonctions :
      - "Définition, dérivé, primitive, limite" : mathematique/definition-derives-primitives-limites.md
      - "Fonctions remarquables" : mathematique/fonctions-remarquables.md
    - Geométrie :  mathematique/geometrie.md
    - Matrice : mathematique/matrice.md
    - "Ajustement" : mathematique/ajustements-modeles.md
    - "Statistique et probabilités" : 
      - Probabilité : mathematique/probabilite.md
      - "Probabilité et statistique" : mathematique/probabilite-statistique.md
      - Statistique : mathematique/statistique.md
      - "Tests statistiques" : mathematique/tests-statistiques.md
  - 'Physique Chimie' :
    - "Unité" :  physique-chimie/unites.md
    - Chimie :
      - "Cinétique" : physique-chimie/chimie/cinetique.md
      - Thermodynamique : physique-chimie/chimie/thermodynamique.md
    - Physique :
      - Physique : physique-chimie/physique/physique.md
      - Optique : physique-chimie/physique/optique.md
  - Autres :
    - Informatique :
        - "Math jax" : informatique/markdown-math.md
        - "Réseau" : informatique/reseau.md
    - Utiles :
        - Emploi : utiles/emploi.md
        - Location : utiles/location.md
    - Communication :
      - Candidater : communication/entretien-embauche.md
      - "Gestion de projet" : communication/gestion-projet.md
      - Rhétorique : communication/rhetorique.md
