site_name: Mes notes
repo_url: https://github.com/gdemare/notes/
repo_name: gdemare/notes
edit_uri: edit/main/docs/

# mkdocs.yml
theme:
  language: fr
  name: "material"
  features:
    - content.tabs.link
    - navigation.tabs #onglet
    - navigation.tabs.sticky #menu avec les onglets tout le temps visible
    - navigation.sections # section dans le menu a gauche
    # - navigation.expand # menu a gauche déroulant ouvert apr défaut
    - navigation.path # affiche le chemin au début de la page.
    - navigation.top # bouton pour remonter en haut
    # - navigation.indexes # pour avoir une page d'index dans chaque partie
    - content.tabs.link
    # - toc.integrate # réuni le plan et le sommaire
    - content.action.edit # bouton edit
    #- content.action.view # bouton voir
  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default 
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to system preference
  theme:
    icon:
      edit: material/pencil

plugins:
  - search
  - mkdocstrings
  - glightbox #pour les images
  - git-revision-date-localized: #pour avoir la date de maj 
      type: date

markdown_extensions:
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.arithmatex:
      generic: true
  - tables
  
extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

nav:
  - Anglais : 
    - Conjugaison : anglais/conjugaison.md
    - Grammaire : anglais/grammaire.md
    - "Ortographe et vocabulaire" : anglais/ortographe-vocabulaire.md
  - Biologie :
    - Bioinformatique :
      - "Séquençage" : biologie/bioinformatique/sequencage.md
    - Cellule :
      - "ADN et ARN" : biologie/cellule/ADN-ARN.md
      - "ADN et ARN synthèse" : biologie/cellule/ADN-ARN-synthese.md
      - Bactéries : biologie/cellule/bacteries.md
      - "Communication cellulaire" : biologie/cellule/communication-cellulaire.md
      - "Cycle cellulaire" : biologie/cellule/cycle-cellulaire.md
      - "Cytosquelette" : biologie/cellule/cytosquelette.md
      - "Matrice extracellulaire et jonctions cellulaires" : biologie/cellule/matrice-extracellulaire-jonctions-cellulaires.md
      - Métabolites : biologie/cellule/metabolites.md
      - Protéines : biologie/cellule/proteines.md
      - "Organisation cellulaire" : biologie/cellule/organisation-cellulaire.md
      - "Régulation de l'expression génétique" : biologie/cellule/regulation-expression-genique.md
    - Ecologie :
      - "Biologie de la conservation" : biologie/ecologie/biologie-conservation.md
      - "Ecologie des communautés" : biologie/ecologie/ecologie-communautes.md
      - "Ecosystème et écologie de la restauration" : biologie/ecologie/ecosysteme-ecologie-restauration.md
      - "Génétique des population" : biologie/ecologie/genetique-population.md
      - "Origine de la biodiversité" : biologie/ecologie/origine-biodiversite.md
    - "Méthodes et techniques" : 
      - "Introduction biologie expérimentale" : biologie/methodes-techniques/introduction-biologie-experiementale.md
      - "Spectrométrie de masse" : biologie/methodes-techniques/spectrometrie.md
    - "Physologie animale" : 
      - 'Structure et fonction' : biologie/physiologie-animale/structure-fonction-principes.md
      - Comportement : biologie/physiologie-animale/comportement.md
      - Histologie  : biologie/physiologie-animale/histologie.md
      - "Osmorégulation et excrétion" : biologie/physiologie-animale/osmoregulation-excretion.md
      - Immunologie : biologie/physiologie-animale/immunologie.md
      - Neurobiologie : biologie/physiologie-animale/neurobiologie.md
      - "Système nerveux" : biologie/physiologie-animale/systeme-nerveux.md
  - Communication :
    - Candidater : communication/entretien-embauche.md
    - "Gestion de projet" : communication/gestion-projet.md
    - Rhétorique : communication/rhetorique.md
  - Mathématique :
    - Mathématique : mathematique/mathematique.md
    - Arithmétique :  mathematique/arithmetique.md
    - Fonctions : mathematique/fonctions.md
    - "Fonctions 2" : mathematique/fonctions_bis.md
    - Geométrie :  mathematique/geometrie.md
    - Modélisation :
      - "Méthodes mixtes" :
        - 'Réseaux de neurones' : mathematique/reseaux-neurones.md
    - "Statistique et probabilités" : 
      - Probabilité : mathematique/probabilite.md
      - Statistique : mathematique/statistique.md
      - "Tests statistiques" : mathematique/tests-statistiques.md
  - 'Physique Chimie' :
    - Chimie : 
      - Thermodynamique : physique-chimie/chimie/thermodynamique.md
      - Biochimie : 
        - Enzymologie : physique-chimie/chimie/biochimie/enzymologie.md
        - "Photosynthèse et métabolisme secondaire" : physique-chimie/chimie/biochimie/photosynthese-metabolisme-secondaire.md
    - Physique :
      - Physique : physique-chimie/physique/physique.md
      - Optique : physique-chimie/physique/optique.md
  - Informatique :
      - 'Math jax' : informatique/markdown-math.md
      - 'Réseau' : informatique/reseau.md
   - Utiles :
      - Emploi : utiles/emploi.md  
      - location : utiles/location.md     	
