site_name: Mes notes
repo_url: https://github.com/gdemare/notes/
repo_name: gdemare/notes
edit_uri: edit/main/docs/

# mkdocs.yml
theme:
  language: fr
  name: "material"
  features:
    - content.action.edit # bouton edit
    - content.action.view # bouton voir
    - content.tabs.link
    - content.code.copy
    - content.tabs.link 
     - toc.integrate # réuni le plan et le sommaire
    - header.autohide
    - navigation.tabs #onglet
    - navigation.tabs.sticky #menu avec les onglets tout le temps visible
    - navigation.sections # section dans le menu a gauche
    # - navigation.expand # menu a gauche déroulant ouvert apr défaut
    - navigation.path # affiche le chemin au début de la page.
    - navigation.top # bouton pour remonter en haut
    # - navigation.indexes # pour avoir une page d'index dans chaque partie
  palette:
      scheme: slate
      primary: indigo
      accent: indigo
  font:
    text: Roboto
    code: Roboto Mono
    
  theme:
    icon:
      edit: material/pencil

plugins:
  - search
  - mkdocstrings
  - glightbox #pour les images
  - git-revision-date-localized: #pour avoir la date de maj 
      type: date

markdown_extensions:
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.arithmatex:
      generic: true
  - tables
  
extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

nav:
  - Biologie :
    - "Biochimie et biomol" :
      - "Biomolécules simples" :  
        - "Panorama" : biologie/biochimie/biomolecules.md
        - "Lipides" : biologie/biochimie/lipides.md
        - "Métabolites" : biologie/biochimie/metabolites.md
        - "Sucres" : biologie/biochimie/sucres.md
      - "ADN et ARN" :
        - "ADN et ARN" : biologie/biochimie/ADN-ARN.md
        - "Synthèse ADN et ARN " : biologie/cellule/ADN-ARN-synthese.md
        - "Etude ARN ADN" : biologie/methodes-techniques/etude_acide_nucleique.md
        - "PCR" : biologie/methodes-techniques/etude_pcr.md
      - "Métabolisme" :  
        - "Réactivité chimique en biologie" : biologie/biochimie/reactivite-chimique-biologie.md
        - "Photosynthèse et métabolisme secondaire" : biologie/metabolisme/photosynthese-metabolisme-secondaire.md
      - "Protéines" : 
        - "Généralités": biologie/biochimie/proteines.md
        - "Enzymes" : biologie/biochimie/enzymes.md
        - "Etude des protéines" : biologie/methodes-techniques/etude_proteines.md
    - Bioinformatique :
      - "Séquençage" : biologie/bioinformatique/alignement-sequence.md
    - "Cellule et tissus" :
      - "Structure et fonctions" :
        - "Structure et fonctions" : biologie/physiologie-animale/structure-fonction-principes.md
        - "Histologie" : biologie/physiologie-animale/histologie.md
      - "Biologie cellulaire" :
        - "Communication cellulaire" : biologie/cellule/communication-cellulaire.md
        - "Cycle cellulaire" : biologie/cellule/cycle-cellulaire.md
        - "Cytosquelette" : biologie/cellule/cytosquelette.md
        - "Matrice extracellulaire et jonctions cellulaires" : biologie/cellule/matrice-extracellulaire-jonctions-cellulaires.md
        - "Organisation cellulaire" : biologie/cellule/organisation-cellulaire.md
        - "Régulation de l'expression génétique" : biologie/cellule/regulation-expression-genique.md
      - "Physologie animale" :
        - "Physologie cellule animale" : biologie/physiologie-animale/physiologie-cellule-animale.md
        - "Comportement" : biologie/physiologie-animale/comportement.md
        - "Nutrition" : biologie/physiologie-animale/nutrition-animaux.md
        - "Immunologie" : biologie/physiologie-animale/immunologie.md
        - "Neurologie" : biologie/physiologie-animale/neurobiologie.md
        - "Osmorégulation et excrétion" : biologie/physiologie-animale/osmoregulation-excretion.md
        - "Système endorinien" : biologie/physiologie-animale/systeme-endocrinien.md
        - "Système nerveux" : biologie/physiologie-animale/systeme-nerveux.md
      - "Procaryotes et virus" :
        - Bactéries : biologie/cellule/bacteries.md
        - Virus : biologie/cellule/virus.md
      - "Techniques" :
        - "Clonage" : biologie/methodes-techniques/clonage.md
        - "Culture cellulaire" : biologie/methodes-techniques/culture-cellulaire.md
        - "Génie génétique" : biologie/methodes-techniques/clonage_genie.md
        - "Histologie" : biologie/methodes-techniques/histologie.md
    - Ecologie :
      - "Populations et communautés" :
        - "Biologie de la conservation" : biologie/ecologie/biologie-conservation.md
        - "Ecologie des communautés" : biologie/ecologie/ecologie-communautes.md
        - "Ecosystème et écologie de la restauration" : biologie/ecologie/ecosysteme-ecologie-restauration.md
        - "Evolution des populations" : biologie/ecologie/evolution-population.md
      - Evolution :
        - "Génétique Mendel" : biologie/evolution/genetique-mendel.md
        - "Génétique des populations" : biologie/ecologie/genetique-population.md
        - "Génome évolution" : biologie/evolution/genome-evolution.md
        - "Phylogénie" : biologie/evolution/phylogenie.md
        - "Origine de la biodiversité" : biologie/ecologie/origine-biodiversite.md
        - "Théorie de l'évolution" : biologie/evolution/theorie-evolution.md
    - "Matériels et méthodes" :
      - "Méthodes" :
        - "Généralités" : biologie/methodes-techniques/etude_biologie.md
        - "Introduction biologie expérimentale" : biologie/methodes-techniques/introduction-biologie-experiementale.md
        - "Immunomarquage" : biologie/methodes-techniques/immunomarquage.md
      - "Matériels" :
        - "Microscopie" : biologie/methodes-techniques/microscopie.md
        - "Imagerie" : biologie/methodes-techniques/imagerie.md
        - "RMN" :  biologie/methodes-techniques/RMN.md
        - "Spectrométrie de masse" : biologie/methodes-techniques/spectrometrie.md
  - "Data Science" :
    - "Panorama" : data-science/methodes-data-science.md
    - "A voir" : data-science/a-voir.md
    - "Dictionnaire Statistique" : data-science/dictionnaire-statistique.md
    - "Données non structurées" :
      - "Cartographie" : data-science/cartographie.md
      - "Fouille de textes" : data-science/text-mining.md
      - "Traitement des images" : data-science/traitement-image.md
      - "Transformation des données" : data-science/transformation-donnees.md
    - "Modèles" :
      - "Classification" :
        - "Classification" : data-science/classification/classification.md
        - "Arbre de décision" : data-science/classification/arbre-de-décision.md
        - "Centroides" : data-science/classification/centroide.md
        - "Classificateur baysien" : data-science/classification/classificateur-baysien.md
        - "Forêt aléatoire" : data-science/classification/forêt-aléatoire.md
        - "Perceptron" : data-science/classification/perceptron.md
        - "Régression logistique" : data-science/classification/regression-logistique.md
      - "Régression" :
        - "Régression" : data-science/classification/regression.md
        - ANOVA : data-science/classification/ANOVA.md
        - "Carte auto adaptative" : data-science/classification/carte-auto-adaptative.md
        - "Espérance maximale" : data-science/classification/espérance-maximisation.md
        - "Régression linéaire" : data-science/classification/regression-lineaire.md
        - "SVM" : data-science/classification/SVM.md
      - "Réseaux de neurones" :
        - "Réseaux de neurones" : data-science/reseaux-neurones/reseaux-neurones.md
        - "Couches convulsives" : data-science/reseaux-neurones/couche-convulsive.md
      - Optimisation : 
        - "Boosting" : data-science/classification/boosting.md      
      - "Série temporelle" :
        - "Série temporelle" : data-science/serie-temporelle.md
        - "ARMA" : data-science/classification/ARMA.md
        - "Lissage exponentiel" : data-science/classification/lissage-exponentiel.md
    - "Descriptions des données" :
      - Cluestering : 
        - Cluestering : data-science/cluestering/cluestering.md
        - "Cluestering des variables" : data-science/classification/clustering-variables.md
        - "CAH" : data-science/cluestering/CAH.md
        - "CFH" : data-science/cluestering/CDH.md
        - "Centres mobiles" : data-science/cluestering/centres-mobiles.md
      - "Réduction de dimensions" :
        - "Réduction de dimensions" : data-science/reduction-dimensions/reduction-dimension.md
        - ACM : data-science/reduction-dimensions/ACM.md
        - ACP : data-science/reduction-dimensions/ACP.md
        - AFC : data-science/reduction-dimensions/AFC.md
        - "Analyse discriminante" : data-science/reduction-dimensions/analyse-discriminante.md
        - "Positionnement multidimensionnel" : data-science/reduction-dimensions/positionnement-multidimensionnel.md
  - Mathématique :
    - "Symboles et notation" : mathematique/mathematique.md
    - Algèbre :
      - Matrice : mathematique/matrice.md
    - Analyse :
      - "Ajustement" : mathematique/ajustements-modeles.md
      - "Optimisation" : mathematique/optimisation.md
      - "Algorithmie" :  mathematique/algorithmique.md
      - "Fonctions" :
        - "Equation différentielle" : mathematique/equation-differentielle.md
        - "Définition, dérivé, primitive, limite" : mathematique/definition-derives-primitives-limites.md
        - "Fonctions remarquables" : mathematique/fonctions-remarquables.md
    - Arithmétique :  mathematique/arithmetique.md
    - Geométrie :  mathematique/geometrie.md
    - "Statistique" : 
      - Probabilité : mathematique/probabilite.md
      - Statistique : 
        - Statistique : mathematique/statistique.md
        - Graphique : data-science/graphiques.md
        - "Tests statistiques" : mathematique/tests-statistiques.md
      - "Probabilité et statistique" : mathematique/probabilite-statistique.md
  - 'Physique Chimie' :
    - "Unité" :  physique-chimie/unites.md
    - Chimie :
      - "Cinétique" : physique-chimie/chimie/cinetique.md
      - Thermodynamique : physique-chimie/chimie/thermodynamique.md
    - Physique :
      - Physique : physique-chimie/physique/physique.md
      - Optique : physique-chimie/physique/optique.md
  - Autres :
    - Anglais : 
      - Conjugaison : anglais/conjugaison.md
      - Grammaire : anglais/grammaire.md
      - "Ortographe et vocabulaire" : anglais/ortographe-vocabulaire.md
    - Informatique :
        - "Base de données" : informatique/database.md
        - "Math jax" : informatique/markdown-math.md
        - "Réseau" : informatique/reseau.md
    - Utiles :
        - Emploi : utiles/emploi.md
        - Location : utiles/location.md
    - Communication :
      - Candidater : communication/entretien-embauche.md
      - "Gestion de projet" : communication/gestion-projet.md
      - Rhétorique : communication/rhetorique.md
