site_name: Mes notes
repo_url: https://gdemare.github.io/notes/

# mkdocs.yml
theme:
  language: fr
  name: "material"
  features:
    - content.tabs.link
    - navigation.tabs #onglet
    - navigation.tabs.sticky #menu avec les onglets tout le temps visible
    - navigation.sections # section dans le menu a gauche
    # - navigation.expand # menu a gauche déroulant ouvert apr défaut
    - navigation.path # affiche le chemin au début de la page.
    - navigation.top # bouton pour remonter en haut
    # - navigation.indexes # pour avoir une page d'index dans chaque partie
    - content.tabs.link
    # - toc.integrate # réuni le plan et le sommaire
  palette:

    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default 
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to system preference

plugins:
  - search
  - mkdocstrings
  - glightbox #pour les images

markdown_extensions:
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.arithmatex:
      generic: true

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

nav:
  - Anglais : 
    - Conjugaison : anglais/conjugaison.md
    - "Ortographe et vocabulaire" : anglais/ortographe-vocabulaire.md
    - Structure : anglais/structure.md
  - Biologie :
    - Bioinformatique :
      - "Séquençage" : biologie/bioinformatique/sequencage.md
    - Cellule :
      - "Protéines" : biologie/cellule/proteines.md
      - "Communication cellulaire" : biologie/cellule/communication-cellulaire.md
    - "Méthodes et techniques" : 
      - "Introduction biologie expérimentale" : biologie/methodes-techniques/introduction-biologie-experiementale.md
      - "Spectrométrie de masse" : biologie/methodes-techniques/spectrometrie.md
  - "Math Physique Chimie" :
    - Chimie :
      - Thermodynamique : math-physique-chimie/chimie/thermodynamique.md
    - 'Mathématique' :
      - 'Mathématique' : math-physique-chimie/mathematique/mathematique.md
      - 'Réseaux de neurones' : math-physique-chimie/mathematique/reseaux-neurones.md
      - Statistique : math-physique-chimie/mathematique/statistique.md
    - Physique :
      - Physique : math-physique-chimie/physique/physique.md
